"""modification de table Test

Revision ID: 0b23c501754a
Revises: d3258b79d033
Create Date: 2025-04-02 13:32:18.240931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b23c501754a'
down_revision = 'd3258b79d033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'site', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('site_id')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
