"""Supprimer la colonne email de la table Etudiant

Revision ID: 11ce58772588
Revises: d79841e6ab85
Create Date: 2025-04-09 16:51:26.311174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11ce58772588'
down_revision = 'd79841e6ab85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=150), nullable=False))
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
