"""Ajout du champ feuille_generee dans test_groupe

Revision ID: 26d13e1de89d
Revises: d83f499c35f0
Create Date: 2025-04-06 16:08:06.634456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26d13e1de89d'
down_revision = 'd83f499c35f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('feuille_generee')

    with op.batch_alter_table('test_groupe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feuille_generee', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_groupe', schema=None) as batch_op:
        batch_op.drop_column('feuille_generee')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feuille_generee', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
