"""Initial migration

Revision ID: 415406fffd4e
Revises: ba056f0a11fd
Create Date: 2026-02-12 14:43:45.834238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415406fffd4e'
down_revision = 'ba056f0a11fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reponse_etudiant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_question', sa.String(length=50), nullable=False),
    sa.Column('choix', sa.String(length=50), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiant.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reponse_etudiant')
    # ### end Alembic commands ###
