"""Ajout de site_id à la table Semestre

Revision ID: ba056f0a11fd
Revises: 11ce58772588
Create Date: 2025-04-10 15:56:29.320323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba056f0a11fd'
down_revision = '11ce58772588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semestre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'site', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semestre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###
