"""ajout de feuille_generee

Revision ID: d83f499c35f0
Revises: 0b23c501754a
Create Date: 2025-04-06 16:04:26.963237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83f499c35f0'
down_revision = '0b23c501754a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feuille_generee', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('feuille_generee')

    # ### end Alembic commands ###
