"""Ajout de la colonne is_active à Teacher

Revision ID: 61a135704eb5
Revises: b3a34bca764d
Create Date: 2025-01-25 20:20:50.501005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a135704eb5'
down_revision = 'b3a34bca764d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
